apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: akri
  namespace: argocd
spec:
  project: default
  destination:
    namespace: default  #update namespace name if you wish
    name: in-cluster   #update cluster name if its different
  source:
    repoURL: https://project-akri.github.io/akri/
    targetRevision: "0.12.20"
    chart: akri
    helm:
      values: |
        akri:
          kubernetesDistro: k3s # Specify Kubernetes distro here: k3s|microk8s|k8s
          udev:
            discovery:
              enabled: true
